### ISSUE TITLE
User management & admin user

### ISSUE THREAD

**Issue by slurdge** [crazy-max/docker-anonaddy#3]
As far as I know, the first user isn't really "admin". Therefore the command to seed the db should probably renamed to "add users" and take user & password as arguments (or a file containing them).
It would also allow creation of user if the configuration of registration is "false" (the default)

**Comment by crazy-max** [comment]
@slurdge

> As far as I know, the first user isn't really "admin".

Admin username is managed through `ANONADDY_ADMIN_USERNAME` env var.

> Therefore the command to seed the db should probably renamed to "add users" and take user & password as arguments (or a file containing them).

I prefer to let the user [create the initial user via the db:seed command](https://github.com/crazy-max/docker-anonaddy#first-launch) for now because there is no other way to do that programmatically. I think it would be better to open an issue on the official repository to have an install command through php artisan like [flarum does](https://github.com/flarum/core/blob/d492579638fb52dafbfe65f1f36a95eb6047f7f3/src/Install/Console/InstallCommand.php).

**Comment by slurdge** [comment]
I agree overall with the approach. Per the maintainer of the official repository, the ANONADDY_ADMIN_USERNAME env file should be set _after_ the db:seed (in case you change the username). So either db::seed takes into account the env variable, or it should be as hardcoded as the db:seed command.

I put the issue here because the php file for seeding is included in the docker image (I suppose you derived it from upstream), so I though it would be needed to change here.

**Comment by crazy-max** [comment]
> I put the issue here because the php file for seeding is included in the docker image (I suppose you derived it from upstream), so I though it would be needed to change here.

It's a dirty workaround ;)
